build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "OpenVDBForUnity/0.0.1"
    CONAN_USERNAME: "kazuki"
    CONAN_LOGIN_USERNAME: "kazuki"
    CONAN_CHANNEL: "development"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: "https://api.bintray.com/conan/kazuki/conan"

    matrix:
       - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
         CONAN_VISUAL_VERSIONS: 12
         CONAN_BUILD_TYPES: Release

       - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
         CONAN_VISUAL_VERSIONS: 14
         CONAN_BUILD_TYPES: Release

       - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
         CONAN_VISUAL_VERSIONS: 15
         CONAN_BUILD_TYPES: Release

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory
  - conan remote add kazuki https://api.bintray.com/conan/kazuki/conan

test_script:
  - python build.py
